export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGOUT = 'LOGOUT';

export const GET_ARTICLES = 'GET_ARTICLES';
export const ARTICLES_RECEIVED = 'ARTICLES_RECEIVED';
export const ARTICLES_NOT_RECEIVED = 'ARTICLES_NOT_RECEIVED';

export const GET__MY_ARTICLES = 'GET_MY_ARTICLES';
export const MY_ARTICLES_RECEIVED = 'CURRENT_ARTICLES_RECEIVED';
export const MY_ARTICLES_NOT_RECEIVED = 'CURRENT_ARTICLES_NOT_RECEIVED';
export const CURRENT_ARTICLE_RECEIVED = 'CURRENT_ARTICLE_RECEIVED';
export const CURRENT_ARTICLE_NOT_RECEIVED = 'CURRENT_ARTICLE_NOT_RECEIVED';
export const RESET_CURRENT_ARTICLE_TO_NULL = 'RESET_CURRENT_ARTICLE_TO_NULL';
export const POST_ARTICLE = 'POST_ARTICLE';
export const ARTICLE_POSTED_SUCCESSFULLY = 'ARTICLE_POSTED_SUCCESSFULLY';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const ARTICLE_DELETED_SUCCESSFULLY = 'ARTICLE_DELETED_SUCCESSFULLY';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const ARTICLE_UPDATED_SUCCESSFULLY = 'ARTICLE_UPDATED_SUCCESSFULLY';
