export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGOUT = 'LOGOUT';

export const GET_ARTICLES = 'GET_ARTICLES';
export const ARTICLES_RECEIVED = 'ARTICLES_RECEIVED';
export const ARTICLES_NOT_RECEIVED = 'ARTICLES_NOT_RECEIVED';